on:
  - push
  - pull_request
name: Test
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello, world!"
      - run: echo "This workflow should not have the Lint annotations"


      # - name: Test this action against an incorrect file.
      #   id: expect-failure
      #   continue-on-error: true
      #   uses: ./
      #   with:
      #     file_glob: ./fixtures/*.yml
      #     spectral_ruleset: .spectral.json

      - if: ${{ failure() }}
        run: exit 0
